# Site
# repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Esteban Alberto Gomez Cifuentes
title: Bioinformatician, PhD
email: eagomezcifuentes@gmail.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  eagomezc
linkedin_username: eagomezc
orcid_username: 0000-0001-8028-416X


# About Section
# about_title: Professional Profile
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Esteban. I'm PhD in science research with expertise in bioinformatics and machine learning applied to immunology, genomics, proteomics, and lipidomics. Experienced in developing predictive tools for health research, analyzing large-scale biological data, and working with programming languages like Python, R and Bash. My strong background in both bioinformatics and lab techniques helps me to bridging multidisciplinary teams to solve complex problems.
 
  I'm currently interested in improving my skills in <mark>machine learning</mark> and developing <mark>Python</mark> applications for biological and health research. 
content:
  - title: Repositories # Title for the section
    layout: list # Type of content section (list/text)
    content:
      # Repository 1
      - layout: top-middle
        title: Machine learning and rheumatoid arthritis treatments
        link: github.com/eagomezc/Machine-Learning-and-RA-treatment
        # link_text: Project Website
        additional_links:
          - title: Machine-Learning-and-RA-treatment
            icon: fab fa-github
            url: github.com/eagomezc/Machine-Learning-and-RA-treatment
        description: | # this will include new lines to allow paragraphs
          This repository contains the script used to study blood pro-resolving mediators as biomarkers to predict the response of DMARD treatment in rheumatoid arthritis patients.
      
      # Repository 2
      - layout: top-middle
        title: Genome association analysis and rheumatoid arthritis
        link: github.com/eagomezc/CG-association-analysis-in-SPM-related-genes
        # link_text: Project Website
        additional_links:
          - title: CG analysis in RA
            icon: fab fa-github
            url: github.com/eagomezc/CG-association-analysis-in-SPM-related-genes
        description: | # this will include new lines to allow paragraphs
          This repository contains the scripts used to study the genetic associations between genetic variant in SPM-related genes and rheumatoid arthritis
        
        # Repository 3
      - layout: top-middle
        title: Retrotransposon database
        link: github.com/eagomezc/Retrotransposon_app
        # link_text: Project Website
        additional_links:
          - title: Retrotransposon_app
            icon: fab fa-github
            url: github.com/eagomezc/Retrotransposon_app
        description: | # this will include new lines to allow paragraphs
          This repository contains the script used for the developing of a web-based application for the identification of retrotransposons in human genomes. 
      
      # Repository 4
      - layout: top-middle
        title: Enriched marine oils supplements effect in human health
        link: github.com/eagomezc/2019_DGE_Correlation_Oil_supplements_study
        # link_text: Project Website
        additional_links:
          - title: Marine oils in human health
            icon: fab fa-github
            url: github.com/eagomezc/2019_DGE_Correlation_Oil_supplements_study
        description: | # this will include new lines to allow paragraphs
          This repository contains the scripts used to run the differential gene expression, GO enrichment and correlation analysis for the paper: "Enriched marine oils supplements increase peripheral blood SPM concentrations and reprogram host immune responses: A randomized double-blind placebo-controlled study"
          
  - title: Experience # Title for the section
    # Experience 1
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Lipid Mediator Unit, QMUL
        link: jdallilab.com/
        sub_title: Staff Scientist/PhD Student/Bioinformatician
        caption: 2018 - Present
        quote: >
          Innovative thinker, bioinformatics solutions, machine learning, wet-lab training
        description: | # this will include new lines to allow paragraphs
         <mark>Machine learning</mark>: I worked with machine learning methodologies: support vector machine, bayesian classifiers, and decision trees (R randomForest and caret, scikit-learn in Python) to predict the response of different treatments in patients with rheumatoid arthritis. The machine learning models were patented.  
         <mark>Network analysis</mark>: I created small tools for the design of biosynthetic networks (Cytoscape, R Shiny) to identify different responses to treatments and up or down-regulation of immunological pathways.
         <mark>Creative problem solving</mark>: The Lipid Mediator Unit is a multidisciplinary team that includes immunologists, chemists and biologists who rely on me to help them with multivariate analysis, statistics, gene expression analysis, data visualization, etc.
         <mark>Lab skills</mark>: As bioinformaticians, it’s important to know where the data comes from; for that reason, I received training in mass spectrometry, flow cytometry, cell isolation and cell culture assays. 
        

    # Experience 2
      - layout: left
        title: Prospection and Design of Biomolecules group, UNAL
        link: ciencias.medellin.unal.edu.co/gruposdeinvestigacion/prospeccionydisenobiomoleculas/
        sub_title: Researcher
        caption: 2015 - 2017
        quote: >
          Fast learner, Proactive, Team work, bioinformatics and databases tools
        description: | # this will include new lines to allow paragraphs
          <mark>Fast learner</mark>: From scratch, I curated and designed a database of antimicrobial peptides (InverPep). I had to learn strategies to organize, curate and build the database. In addition to this, I developed a friendly user interface. 
          <mark>Proactive</mark>: The identification of bioactive peptides in proteomes was done manually. I developed a tool (PepMultiFinder) that based on physicochemical properties automatically identifies antimicrobial peptides. 
 
 - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
    #Education 1
      - layout: left
        title: Queen Mary University of London
        caption: 2019 - 2024
        sub_title: PhD Biochemical Pharmacology
        quote: >
         Doctor of Philosophy (Focused in Bioinformatics). 
        description: | # this will include new lines to allow paragraphs
          <mark>PhD thesis</mark>: Exploring the potential of specialized pro-resolving mediator biology in understanding the development and progression of inflammatory diseases using bioinformatics.
          <mark>Technicals system used</mark>: Univariate and multivariate analysis (PCA, PLS-DA, correlation analysis), machine learning (Bayesian classifiers, Random forest, LASSO, SVM), HPC (LSF), RNA (Bulk and scRNA-Seq) data analysis (multiQC, STAR reads mapping, FeatureCount alignment, R Seurat), Differential Gene Expression analysis (EdgeR), Genome and Pheno-wide association analysis (UK Biobank, PLINK, Python, Linux, Bash, Anaconda), GO enrichment, Network and pathway analysis (Cytoscape, R Shiny, STRING, KEGG, Reactome), flow cytometry and liquid chromatography-mass spectrometry (lipidomics).  
          <mark>Supervision experience</mark>: I mentored three master's students who were doing their master's dissertations in bioinformatics at QMUL. 
    
    #Education 2
    - layout: left
        title: Queen Mary University of London
        caption: 2017 - 2018
        sub_title: MSc. Bioinformatics
        quote: >
         Master in Science with an average of 82.37/100 equivalent to a Distinction. 
        description: | # this will include new lines to allow paragraphs
          <mark>Master dissertation</mark>: Searching for signatures of selection in a highly social insect – A population-genomics analysis. Ecology, evolution, genome-wide screening and genome assembly.
          <mark>Developed Software - Database</mark>: Retrotransposon: a web-based database for the collection, identification and analysis of retrotransposons (SQLite, Flask, HTML, R).  
          <mark>Relevant modules</mark>: Genome Bioinformatics, Coding for Scientifics, Post-Genomics Bioinformatics and Statistics.
          <mark>Technicals system used</mark>: Genome assembly programs (SOAPdenovo and Masurca), Python (flow control, functions, objects, biopython), R and RStudio, machine learning, Proteomics tools (MetaboAnalysti, Expasy, I-Tasser). 
# Footer
footer_show_references: true
references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
