# Site
# repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Esteban Alberto Gomez Cifuentes
title: Bioinformatician, PhD
email: eagomezcifuentes@gmail.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  eagomezc
linkedin_username: eagomezc
orcid_username: 0000-0001-8028-416X


# About Section
# about_title: Professional Profile
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Esteban. I'm PhD in science research with expertise in bioinformatics and machine learning applied to immunology, genomics, proteomics, and lipidomics. Experienced in developing predictive tools for health research, analyzing large-scale biological data, and working with programming languages like Python, R and Bash. My strong background in both bioinformatics and lab techniques helps me to bridging multidisciplinary teams to solve complex problems.
 
  I'm currently interested in improving my skills in <mark>machine learning</mark> and developing <mark>Python</mark> applications for biological and health research. 
content:
  - title: Repositories # Title for the section
    layout: list # Type of content section (list/text)
    content:
      # Repository 1
      - layout: top-middle
        title: Machine learning and rheumatoid arthritis treatments
        link: github.com/eagomezc/Machine-Learning-and-RA-treatment
        # link_text: Project Website
        additional_links:
          - title: Machine-Learning-and-RA-treatment
            icon: fab fa-github
            url: github.com/eagomezc/Machine-Learning-and-RA-treatment
        description: | # this will include new lines to allow paragraphs
          This repository contains the script used to study blood pro-resolving mediators as biomarkers to predict the response of DMARD treatment in rheumatoid arthritis patients.
      
      # Repository 2
      - layout: top-middle
        title: Genome association analysis and rheumatoid arthritis
        link: github.com/eagomezc/CG-association-analysis-in-SPM-related-genes
        # link_text: Project Website
        additional_links:
          - title: CG analysis in RA
            icon: fab fa-github
            url: github.com/eagomezc/CG-association-analysis-in-SPM-related-genes
        description: | # this will include new lines to allow paragraphs
          This repository contains the scripts used to study the genetic associations between genetic variant in SPM-related genes and rheumatoid arthritis
        
        # Repository 3
      - layout: top-middle
        title: Retrotransposon database
        link: github.com/eagomezc/Retrotransposon_app
        # link_text: Project Website
        additional_links:
          - title: Retrotransposon_app
            icon: fab fa-github
            url: github.com/eagomezc/Retrotransposon_app
        description: | # this will include new lines to allow paragraphs
          This repository contains the script used for the developing of a web-based application for the identification of retrotransposons in human genomes. 
      
      # Repository 4
      - layout: top-middle
        title: Enriched marine oils supplements effect in human health
        link: github.com/eagomezc/2019_DGE_Correlation_Oil_supplements_study
        # link_text: Project Website
        additional_links:
          - title: Marine oils in human health
            icon: fab fa-github
            url: github.com/eagomezc/2019_DGE_Correlation_Oil_supplements_study
        description: | # this will include new lines to allow paragraphs
          This repository contains the scripts used to run the differential gene expression, GO enrichment and correlation analysis for the paper: "Enriched marine oils supplements increase peripheral blood SPM concentrations and reprogram host immune responses: A randomized double-blind placebo-controlled study"
          
  
# Footer
footer_show_references: true
#references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
